# The Docker image that will be used to build your app
image: alpine:latest
pages:  # a predefined job that builds your pages and saves them to the specified path.
  script:
    - echo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
